### ISSUE TITLE
Much of the code here can be removed

### ISSUE THREAD

**Issue by cweagans** [rajeshreeputra/composer-dynamic-patches#1]
You've got a lot of extra stuff in this repo. The only stuff you need is this:

* https://github.com/rajeshreeputra/composer-dynamic-patching/blob/develop/src/Plugin/Plugin.php#L126-L133
* https://github.com/rajeshreeputra/composer-dynamic-patching/blob/develop/src/Capability/Resolver/DynamicPatchingResolverProvider.php
* https://github.com/rajeshreeputra/composer-dynamic-patching/blob/develop/src/Resolver/DynamicPatchingPatchesFile.php

You can get rid of https://github.com/rajeshreeputra/composer-dynamic-patching/blob/develop/src/Patch.php by using the `$extra` attribute in the existing patch class: https://github.com/cweagans/composer-patches/blob/main/src/Patch.php#L59  If you use the [expanded patch format](https://docs.cweagans.net/composer-patches/usage/defining-patches/#expanded-format), you can put the version in the `extra` key and have your resolver filter them down before handing them off to the patch collection.

This makes the patch definitions a little more verbose, but it should make your life a little easier.

Let me know if you have questions on any of this. No worries if you don't want to make any of those changes -- just trying to make your life easier :)

Oh! One other thing: as far as I know, you're the first "contrib" plugin for composer patches. If you set up some tests, I'd be happy to run them as part of a pre-release Composer Patches test pipeline (to validate that future versions of Composer Patches don't break your plugin). I'd also be interested in adding a "Third party plugins" page to the documentation that links to this plugin with some information about what it does. If you'd like to do either of those things, let me know!

**Comment by rajeshreeputra** [comment]
Thank you, @cweagans, for your insightful review of the plugin. I would be grateful if we could have this plugin added to the 'Third-Party Plugins' page.
Created [PR](https://github.com/rajeshreeputra/composer-dynamic-patching/pull/2) to incorporate your feedback.

**Comment by rajeshreeputra** [comment]
@cweagans updated the plugin to remove unused code, please have a look at it whenever you get some time.

**Comment by rajeshreeputra** [comment]
PR merged, hence closing.
